- hosts: all
  vars:
    root_password: '$6$Vso6nYhh3EUSTvgL$ugX1MRAF2UbVlhJr6S3t/qYUUuY6Zkhk3BFInBlvfGSTHcrnAnvfvTRVLkZZFEmCo3izWJ1vLeCa83zcy84Vl1'

  tasks:
  - name: Change root password
    user: name=root password="{{ root_password }}"

